import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Footer, InfoPanel, Navbar } from "@/components";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "1Doc Blog",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
    <html lang={locale} data-theme="light" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} sm:overflow-hidden antialiased  !px-4 !py-5 text-black dark:bg-background dark:text-white`}
      >
        <NextIntlClientProvider locale="uz" messages={messages}>
          <div className="flex flex-col w-full gap-3">
            <InfoPanel />
            <Navbar />
            {children}
            <footer className="flex w-full">
              <Footer />
            </footer>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
